### ISSUE TITLE
JS: have to click button twice to do a GET request

### ISSUE THREAD

**Issue by benocd** [benocd/rehuen#1]
When changing months I have to click the select button twice to load the required json dataset. Any help is welcome :)

**Comment by pille1842** [comment]
I'll have a look at that in a few hours!

**Comment by DillonSimeone** [comment]
I'm fiddling with the codes now. I was able to reproduce the bug, so I should be able to track it down.

**Comment by DillonSimeone** [comment]
I solved it. Making the pull request now. Pushing buttons...

**Comment by DillonSimeone** [comment]
Pull request made.

https://github.com/benocd/rehuen/pull/2

**Comment by benocd** [comment]
@DillonSimeone You are a legend! Thanks buddy
